app/accounts/urls.py
from django.urls import path
from accounts.views import MyProfileView, SignUpView, ActivateUserView

app_name = 'accounts'

urlpatterns = [
    # path('my-profile/<int:pk>/', MyProfileView.as_view(), name='my-profile'),
    path('my-profile/', MyProfileView.as_view(), name='my-profile'),
    path('sign-up/', SignUpView.as_view(), name='sign-up'),
    path('activate/<uuid:username>/', ActivateUserView.as_view(), name='activate-user'),
]

app/currency/urls.py
from currency.views import (
    GeneratePasswordView,
    RateListView, response_codes, RateCreateView,
    RateDetailView, RateUpdateView,
    RateDeleteView, ContactUsCreateView,
    SourceDetailView, SourceListView,
    LatestRatesView,
    # rates_list_api_example,
)
from django.urls import path

app_name = 'currency'

urlpatterns = [
    # currency
    # path('rate/list/', rate_list),
    # path('rate/create/', rate_create, name='rate-create'),
    # path('rate/details/<int:rate_id>/', rate_details),
    # path('rate/update/<int:rate_id>/', rate_update),
    # path('rate/delete/<int:rate_id>/', rate_delete),

    path('rate/list/', RateListView.as_view(), name='rate-list'),
    path('rate/create/', RateCreateView.as_view(), name='rate-create'),
    path('rate/details/<int:pk>/', RateDetailView.as_view(), name='rate-details'),
    path('rate/update/<int:pk>/', RateUpdateView.as_view(), name='rate-update'),
    path('rate/delete/<int:pk>/', RateDeleteView.as_view(), name='rate-delete'),
    path('rate/latest/', LatestRatesView.as_view(), name='rate-latest'),

    path('contactus/create/', ContactUsCreateView.as_view(), name='contactus-create'),

    path('source/details/<int:pk>/', SourceDetailView.as_view(), name='source-details'),
    path('source/list/', SourceListView.as_view(), name='source-list'),

    path('response-codes/', response_codes),
    path('gen-pass/', GeneratePasswordView.as_view()),

    # API example
    # path('api/rate/list/', rates_list_api_example),
]

app/settings/urls.py
import debug_toolbar
from django.conf.urls import url
from django.urls import include, path
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Open Rates API",
        default_version='v1',
        description="Current Bank Rates",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', TemplateView.as_view(template_name='index.html'), name='index'),

    path('auth/', include('django.contrib.auth.urls')),

    path('currency/', include('currency.urls')),
    path('accounts/', include('accounts.urls')),
    path('api/v1/', include('api.v1.urls')),  # 10
    # path('api/v2/', include('api.v2.urls')),  # 9_990
    path('__debug__/', include(debug_toolbar.urls)),

    # API docs
    url(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    url(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    url(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

urlpatterns += [path('silk/', include('silk.urls', namespace='silk'))]

urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

app/currency/models.py
from django.db import models
from django.templatetags.static import static

from currency import model_choices as mch


class Source(models.Model):
    name = models.CharField(max_length=64)
    code_name = models.CharField(max_length=24, unique=True, editable=False)

    logo = models.FileField(
        upload_to=f'sources/logo',
        blank=True,
        null=True,
        default=None,
    )

    # .get_{filed_name}_display()

    def get_logo(self):
        if self.logo:
            return self.logo.url
        return static('images/source-default.png')


# Model
class Rate(models.Model):
    sale = models.DecimalField(max_digits=5, decimal_places=2)
    buy = models.DecimalField(max_digits=5, decimal_places=2)
    created = models.DateTimeField(auto_now_add=True)
    source = models.ForeignKey(
        Source,
        related_name='rates',
        on_delete=models.CASCADE,
    )   # source_id
    type = models.CharField(
        max_length=3,
        choices=mch.RATE_TYPES,
        blank=False,
        null=False,
        default=mch.TYPE_USD,
    )


class ContactUs(models.Model):
    email_to = models.EmailField()
    subject = models.CharField(max_length=255)
    body = models.CharField(max_length=2056)
    created = models.DateTimeField(auto_now_add=True)


class ResponseLog(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    status_code = models.PositiveSmallIntegerField()
    path = models.CharField(max_length=255)
    request_method = models.CharField(max_length=255, choices=mch.METHODS, default='GET')
    response_time = models.PositiveSmallIntegerField(
        help_text='in milliseconds.'
    )
    # request_method = ('GET', 'POST') - choices

'''
Customers
id    |    name
1     |    Dmytro Kaminskyi
2     |    Alex R

Orders
id    |    ProductName    |     CustomerId (integer)
1     |    Laptop         |     1
2     |    TV             |     1

=========================================

user
id   | name
1    | Dmytro K
2    | Alex R
3    | Nikolay H

books
id   |   name    |   user_id (int)
1    |   LOTR    |     1
4    |   CCCCCCC |     1
5    |   DDDDDDD |     2
6    |   EEEEEEE |     null



Rate
id  |  buy   |   sale   |   source_id
1   |  23    |   24    |       1
2   |  24    |   25    |       1
3   |  25    |   26    |       1
4   |  25    |   26    |       2

Source
id   |  name
1    |  privatbank
2    |  monobank

OneToOne
OneToMany
ManyToMany
'''

app/currency/forms.py
from django import forms

from currency.models import Rate


class RateForm(forms.ModelForm):
    class Meta:
        model = Rate
        fields = (
            'buy',
            'sale',
            'source',
            'type',
        )

app/currency/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from urllib.parse import urlencode

from currency.filters import RateFilter
from currency.services import get_latest_rates
from currency.tasks import contact_us

from currency.utils import generate_password as gen_pass
from currency.models import Rate, ContactUs, Source
from currency.forms import RateForm
from django.views.generic import (
    ListView, CreateView, DetailView, UpdateView,
    DeleteView, TemplateView
)

from django_filters.views import FilterView

from django.http import HttpResponse

from mixins import AllowSuperuserMixin


class GeneratePasswordView(TemplateView):
    template_name = 'generate_password.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        password_len = int(self.request.GET.get('password-len'))
        context['password'] = gen_pass(password_len)

        return context


class RateListView(FilterView):
    queryset = Rate.objects.all().defer('created').select_related('source').order_by('-created')
    template_name = 'rate_list.html'
    paginate_by = 25
    filterset_class = RateFilter

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        get_parameters = {}
        for key, value in self.request.GET.items():
            if key != 'page':
                get_parameters[key] = value

        context['pagination_params'] = urlencode(get_parameters)

        return context


class RateCreateView(CreateView):
    # model = Rate
    queryset = Rate.objects.all()
    form_class = RateForm
    success_url = reverse_lazy('currency:rate-list')
    template_name = 'rate_create.html'


class RateDetailView(LoginRequiredMixin, DetailView):
    queryset = Rate.objects.all()
    template_name = 'rate_details.html'


class RateUpdateView(AllowSuperuserMixin, UpdateView):
    queryset = Rate.objects.all()
    form_class = RateForm
    success_url = reverse_lazy('currency:rate-list')
    template_name = 'rate_update.html'


class RateDeleteView(AllowSuperuserMixin, DeleteView):
    queryset = Rate.objects.all()
    success_url = reverse_lazy('currency:rate-list')
    template_name = 'rate_delete.html'


class ContactUsCreateView(CreateView):
    model = ContactUs
    success_url = reverse_lazy('index')
    template_name = 'contactus_create.html'
    fields = (
        'email_to',
        'subject',
        'body',
    )

    def form_valid(self, form):
        subject = form.cleaned_data['subject']
        body = form.cleaned_data['body']
        email_to = form.cleaned_data['email_to']

        full_email_body = f'''
        Email From: {email_to}
        Body: {body}
        '''
        contact_us.apply_async(args=(subject, full_email_body))

        return super().form_valid(form)

class SourceDetailView(DetailView):
    queryset = Source.objects.all()
    template_name = 'source_details.html'


class SourceListView(ListView):
    # queryset = Source.objects.all().prefetch_related('rates')
    queryset = Source.objects.all()
    template_name = 'source_list.html'


class LatestRatesView(TemplateView):
    template_name = 'latest_rates.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rate_list'] = get_latest_rates()
        return context

# def rates_list_api_example(request):
#     import json
#
#     rates = Rate.objects.all()
#     result = []
#     for rate in rates:
#         result.append({
#             'id': rate.id,
#             'buy': float(rate.buy),
#             'sale': float(rate.sale),
#         })
#
#     # return HttpResponse(json.dumps(result), content_type='application/json')
#     return JsonResponse(result, safe=False)


def response_codes(request):
    '''
    Informational
    1xx
    101 - connected

    Success
    2xx
    200 - Ok
    201 - Created
    202 - Accepted

    Redirect
    3xx
    301 - Permanent
    302 - temporary

    Client Errors
    4xx
    400 - Bad Request
    404 - Not Found (page, resource, object)

    Server Error
    5xx
    500 - Server Error
    502 - server not available
    '''
    from time import sleep
    sleep(5)

    response = HttpResponse('Status Code', status=404)
    return response

app/currency/templates/includes/messages.html
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}

app/currency/templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" href="{% url 'index' %}">Home</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText"
            aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'currency:rate-list' %}">Rate List</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'currency:source-list' %}">Source List</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'currency:rate-latest' %}">Latest Rates</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'currency:contactus-create' %}">Contact US</a>
            </li>

        </ul>
        <span class="navbar-text">
        {% if request.user.is_authenticated %}
            {{ request.user.email }}
            <a class="btn btn-link" href="{% url 'password_change' %}" >Change Password</a>
            <a class="btn btn-link" href="{% url 'accounts:my-profile' %}" >My Profile</a>
            <a class="btn btn-link" href="{% url 'logout' %}">Log Out</a>
        {% else %}
            <a class="btn btn-warning" href="{% url 'accounts:sign-up' %}">SignUp</a>
            <a class="btn btn-link" href="{% url 'login' %}">Login</a>
        {% endif %}
        </span>
    </div>
</nav>

app/currency/templates/includes/paginator.html
<ul class="pagination">

    {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}&{{ pagination_params }}" tabindex="-1">Previous</a>
        </li>
    {% endif %}

    {% for page_index in page_obj.paginator.page_range %}
        <li class="page-item {% if page_obj.number ==  page_index %}active{% endif %}">
            <a class="page-link" href="?page={{ page_index }}&{{ pagination_params }}">
                {{ page_index }}
            </a>
        </li>
    {% endfor %}

    {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}&{{ pagination_params }}">Next</a>
        </li>
    {% endif %}

</ul>