app/accounts/urls.py
from django.urls import path
from accounts.views import MyProfileView, SignUpView, ActivateUserView

app_name = 'accounts'

urlpatterns = [
    # path('my-profile/<int:pk>/', MyProfileView.as_view(), name='my-profile'),
    path('my-profile/', MyProfileView.as_view(), name='my-profile'),
    path('sign-up/', SignUpView.as_view(), name='sign-up'),
    path('activate/<uuid:username>/', ActivateUserView.as_view(), name='activate-user'),
]

app/currency/urls.py
from currency.views import (
    GeneratePasswordView,
    RateListView, response_codes, RateCreateView,
    RateDetailView, RateUpdateView,
    RateDeleteView, ContactUsCreateView,
    SourceDetailView, SourceListView,
    LatestRatesView,
    # rates_list_api_example,
)
from django.urls import path

app_name = 'currency'

urlpatterns = [
    # currency
    # path('rate/list/', rate_list),
    # path('rate/create/', rate_create, name='rate-create'),
    # path('rate/details/<int:rate_id>/', rate_details),
    # path('rate/update/<int:rate_id>/', rate_update),
    # path('rate/delete/<int:rate_id>/', rate_delete),

    path('rate/list/', RateListView.as_view(), name='rate-list'),
    path('rate/create/', RateCreateView.as_view(), name='rate-create'),
    path('rate/details/<int:pk>/', RateDetailView.as_view(), name='rate-details'),
    path('rate/update/<int:pk>/', RateUpdateView.as_view(), name='rate-update'),
    path('rate/delete/<int:pk>/', RateDeleteView.as_view(), name='rate-delete'),
    path('rate/latest/', LatestRatesView.as_view(), name='rate-latest'),

    path('contactus/create/', ContactUsCreateView.as_view(), name='contactus-create'),

    path('source/details/<int:pk>/', SourceDetailView.as_view(), name='source-details'),
    path('source/list/', SourceListView.as_view(), name='source-list'),

    path('response-codes/', response_codes),
    path('gen-pass/', GeneratePasswordView.as_view()),

    # API example
    # path('api/rate/list/', rates_list_api_example),
]

app/settings/urls.py
import debug_toolbar
from django.conf.urls import url
from django.urls import include, path
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Open Rates API",
        default_version='v1',
        description="Current Bank Rates",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', TemplateView.as_view(template_name='index.html'), name='index'),

    path('auth/', include('django.contrib.auth.urls')),

    path('currency/', include('currency.urls')),
    path('accounts/', include('accounts.urls')),
    path('api/v1/', include('api.v1.urls')),  # 10
    # path('api/v2/', include('api.v2.urls')),  # 9_990
    path('__debug__/', include(debug_toolbar.urls)),

    # API docs
    url(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    url(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    url(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

urlpatterns += [path('silk/', include('silk.urls', namespace='silk'))]

urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

app/currency/models.py
from django.db import models
from django.templatetags.static import static

from currency import model_choices as mch


class Source(models.Model):
    name = models.CharField(max_length=64)
    code_name = models.CharField(max_length=24, unique=True, editable=False)

    logo = models.FileField(
        upload_to=f'sources/logo',
        blank=True,
        null=True,
        default=None,
    )

    # .get_{filed_name}_display()

    def get_logo(self):
        if self.logo:
            return self.logo.url
        return static('images/source-default.png')


# Model
class Rate(models.Model):
    sale = models.DecimalField(max_digits=5, decimal_places=2)
    buy = models.DecimalField(max_digits=5, decimal_places=2)
    created = models.DateTimeField(auto_now_add=True)
    source = models.ForeignKey(
        Source,
        related_name='rates',
        on_delete=models.CASCADE,
    )   # source_id
    type = models.CharField(
        max_length=3,
        choices=mch.RATE_TYPES,
        blank=False,
        null=False,
        default=mch.TYPE_USD,
    )


class ContactUs(models.Model):
    email_to = models.EmailField()
    subject = models.CharField(max_length=255)
    body = models.CharField(max_length=2056)
    created = models.DateTimeField(auto_now_add=True)


class ResponseLog(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    status_code = models.PositiveSmallIntegerField()
    path = models.CharField(max_length=255)
    request_method = models.CharField(max_length=255, choices=mch.METHODS, default='GET')
    response_time = models.PositiveSmallIntegerField(
        help_text='in milliseconds.'
    )
    # request_method = ('GET', 'POST') - choices

'''
Customers
id    |    name
1     |    Dmytro Kaminskyi
2     |    Alex R

Orders
id    |    ProductName    |     CustomerId (integer)
1     |    Laptop         |     1
2     |    TV             |     1

=========================================

user
id   | name
1    | Dmytro K
2    | Alex R
3    | Nikolay H

books
id   |   name    |   user_id (int)
1    |   LOTR    |     1
4    |   CCCCCCC |     1
5    |   DDDDDDD |     2
6    |   EEEEEEE |     null



Rate
id  |  buy   |   sale   |   source_id
1   |  23    |   24    |       1
2   |  24    |   25    |       1
3   |  25    |   26    |       1
4   |  25    |   26    |       2

Source
id   |  name
1    |  privatbank
2    |  monobank

OneToOne
OneToMany
ManyToMany
'''

app/currency/forms.py
from django import forms

from currency.models import Rate


class RateForm(forms.ModelForm):
    class Meta:
        model = Rate
        fields = (
            'buy',
            'sale',
            'source',
            'type',
        )

app/currency/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from urllib.parse import urlencode

from currency.filters import RateFilter
from currency.services import get_latest_rates
from currency.tasks import contact_us

from currency.utils import generate_password as gen_pass
from currency.models import Rate, ContactUs, Source
from currency.forms import RateForm
from django.views.generic import (
    ListView, CreateView, DetailView, UpdateView,
    DeleteView, TemplateView
)

from django_filters.views import FilterView

from django.http import HttpResponse

from mixins import AllowSuperuserMixin


class GeneratePasswordView(TemplateView):
    template_name = 'generate_password.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        password_len = int(self.request.GET.get('password-len'))
        context['password'] = gen_pass(password_len)

        return context


class RateListView(FilterView):
    queryset = Rate.objects.all().defer('created').select_related('source').order_by('-created')
    template_name = 'rate_list.html'
    paginate_by = 25
    filterset_class = RateFilter

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        get_parameters = {}
        for key, value in self.request.GET.items():
            if key != 'page':
                get_parameters[key] = value

        context['pagination_params'] = urlencode(get_parameters)

        return context


class RateCreateView(CreateView):
    # model = Rate
    queryset = Rate.objects.all()
    form_class = RateForm
    success_url = reverse_lazy('currency:rate-list')
    template_name = 'rate_create.html'


class RateDetailView(LoginRequiredMixin, DetailView):
    queryset = Rate.objects.all()
    template_name = 'rate_details.html'


class RateUpdateView(AllowSuperuserMixin, UpdateView):
    queryset = Rate.objects.all()
    form_class = RateForm
    success_url = reverse_lazy('currency:rate-list')
    template_name = 'rate_update.html'


class RateDeleteView(AllowSuperuserMixin, DeleteView):
    queryset = Rate.objects.all()
    success_url = reverse_lazy('currency:rate-list')
    template_name = 'rate_delete.html'


class ContactUsCreateView(CreateView):
    model = ContactUs
    success_url = reverse_lazy('index')
    template_name = 'contactus_create.html'
    fields = (
        'email_to',
        'subject',
        'body',
    )

    def form_valid(self, form):
        subject = form.cleaned_data['subject']
        body = form.cleaned_data['body']
        email_to = form.cleaned_data['email_to']

        full_email_body = f'''
        Email From: {email_to}
        Body: {body}
        '''
        contact_us.apply_async(args=(subject, full_email_body))

        return super().form_valid(form)

class SourceDetailView(DetailView):
    queryset = Source.objects.all()
    template_name = 'source_details.html'


class SourceListView(ListView):
    # queryset = Source.objects.all().prefetch_related('rates')
    queryset = Source.objects.all()
    template_name = 'source_list.html'


class LatestRatesView(TemplateView):
    template_name = 'latest_rates.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['rate_list'] = get_latest_rates()
        return context

# def rates_list_api_example(request):
#     import json
#
#     rates = Rate.objects.all()
#     result = []
#     for rate in rates:
#         result.append({
#             'id': rate.id,
#             'buy': float(rate.buy),
#             'sale': float(rate.sale),
#         })
#
#     # return HttpResponse(json.dumps(result), content_type='application/json')
#     return JsonResponse(result, safe=False)


def response_codes(request):
    '''
    Informational
    1xx
    101 - connected

    Success
    2xx
    200 - Ok
    201 - Created
    202 - Accepted

    Redirect
    3xx
    301 - Permanent
    302 - temporary

    Client Errors
    4xx
    400 - Bad Request
    404 - Not Found (page, resource, object)

    Server Error
    5xx
    500 - Server Error
    502 - server not available
    '''
    from time import sleep
    sleep(5)

    response = HttpResponse('Status Code', status=404)
    return response

app/currency/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Title</title>

    <link rel="stylesheet" href="{% static 'styles/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'styles/main.css' %}">
</head>
<body>

{% include 'includes/messages.html' %}

{% include 'includes/navbar.html' %}

<div class="container">
    {% block main_content %}
    {% endblock %}
</div>

<script src="{% static 'scripts/jquery-3.5.1.slim.min.js' %}"></script>
<script src="{% static 'scripts/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

app/currency/templates/contactus_create.html
{% extends 'base.html' %}

{% block main_content %}

Contact Us

<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Submit</button>
</form>

{% endblock %}

app/currency/templates/generate_password.html
{% extends 'base.html' %}

{% block main_content %}

Generate Password

Your Password: {{ password }}

{% endblock %}

app/currency/templates/index.html
{% extends 'base.html' %}

{% block main_content %}

<div class="row">
    <div class="col">{% lorem %}</div>
    <div class="col">{% lorem %}</div>
    <div class="col">{% lorem %}</div>
</div>
{% endblock %}

app/currency/templates/latest_rates.html
{% extends 'base.html' %}

{% block main_content %}

<a href="{% url 'currency:rate-create' %}">Create Rate</a>

<table class="table table-striped">
  <tr>
    <th>ID</th>
    <th>Sale</th>
    <th>Buy</th>

    <th>Type</th>
    <th>Source</th>
  </tr>

  {% for rate in rate_list %}
  <tr>
    <td>{{ rate.id }}</td>
    <td>{{ rate.sale }}</td>
    <td>{{ rate.buy }}</td>
    <td>{{ rate.get_type_display }}</td>
    <td><a href="{% url 'currency:source-details' rate.source_id %}">{{ rate.source_id }}</a></td>
  </tr>
  {% endfor %}
</table>

{% endblock %}

app/currency/templates/rate_create.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block main_content %}

    Create Rate

    <div class="row">
        <div class="col-6">
            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-primary">Send To Django Server</button>
            </form>
        </div>
    </div>

{% endblock %}

app/currency/templates/rate_delete.html
{% extends 'base.html' %}

{% block main_content %}

Are you sure you want to delete rate with id: {{ object.id }}?

<form method="post">
  {% csrf_token %}
  <button type="submit">Delete</button>
</form>

{% endblock %}

app/currency/templates/rate_details.html
{% extends 'base.html' %}

{% block main_content %}

Rate Details

Id: {{ object.id }}<br>
Buy: {{ object.buy }}<br>
Sale: {{ object.sale }}<br>
Create: {{ object.created }}<br>
Source: {{ object.source }}<br>
Type: {{ object.type }}<br>

{% endblock %}

app/currency/templates/rate_list.html
{% extends 'base.html' %}

{% block main_content %}

    <a class="btn btn-primary" href="{% url 'currency:rate-create' %}">Create Rate</a>

    <form method="get">
        {{ filter.form.as_p }}
        <button type="submit">Submit</button>
    </form>

    <table class="table table-striped">
        <tr>
            <th>ID</th>
            <th>Sale</th>
            <th>Buy</th>

            <th>Type</th>
            <th>Source</th>
            <th>Created</th>
            <th>Source Logo</th>
            <th>Actions</th>
        </tr>

        {% for rate in rate_list %}
            <tr>
                <td>{{ rate.id }}</td>
                <td>{{ rate.sale }}</td>
                <td>{{ rate.buy }}</td>
                <td>{{ rate.get_type_display }}</td>
                <td><a href="{% url 'currency:source-details' rate.source_id %}">{{ rate.source.name }}</a></td>
                <td>{{ rate.created }}</td>
                <td><img src="{{ rate.source.get_logo }}" alt="source logo" width="50" height="50"/></td>
                <td>
                    {% if request.user.is_authenticated %}
                    <div class="dropdown">
                        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton"
                                data-toggle="dropdown"
                                aria-haspopup="true" aria-expanded="false">
                            Actions
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item" href="{% url 'currency:rate-details' rate.pk %}">Details</a>
                            {% if request.user.is_superuser %}
                                <a class="dropdown-item" href="{% url 'currency:rate-update' rate.pk %}">Update</a>
                                <a class="dropdown-item" href="{% url 'currency:rate-delete' rate.pk %}">Delete</a>
                            {% endif %}
                        </div>
                    </div>
                    {% else %}
                        No actions allowed
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
    </table>

    {% include 'includes/paginator.html' %}

{% endblock %}

app/currency/templates/rate_update.html
{% extends 'base.html' %}

{% block main_content %}

Update Rate

<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Send To Django Server</button>
</form>

{% endblock %}

app/currency/templates/source_details.html
{% extends 'base.html' %}

{% block main_content %}

    Source Details

    Id: {{ object.id }}<br>
    Name: {{ object.name }}<br>

    Related Rates
    <table class="table table-striped">
        <tr>
            <th>ID</th>
            <th>Sale</th>
            <th>Buy</th>

            <th>Type</th>
            <th>Actions</th>
        </tr>

        {% for rate in object.rates.all %}
            <tr>
                <td>{{ rate.id }}</td>
                <td>{{ rate.sale }}</td>
                <td>{{ rate.buy }}</td>
                <td>{{ rate.get_type_display }}</td>
                <td>
                    <div class="dropdown">
                        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton"
                                data-toggle="dropdown"
                                aria-haspopup="true" aria-expanded="false">
                            Actions
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item" href="{% url 'currency:rate-details' rate.pk %}">Details</a>
                            <a class="dropdown-item" href="{% url 'currency:rate-update' rate.pk %}">Update</a>
                            <a class="dropdown-item" href="{% url 'currency:rate-delete' rate.pk %}">Delete</a>
                        </div>
                    </div>
                </td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

app/currency/templates/source_list.html
{% extends 'base.html' %}

{% block main_content %}

    {% for object in object_list %}
        Id: {{ object.id }}<br>
        Name: {{ object.name }}<br>

        Related Rates
        <table class="table table-striped">
            <tr>
                <th>ID</th>
                <th>Sale</th>
                <th>Buy</th>

                <th>Type</th>
                <th>Actions</th>
            </tr>

            {% for rate in object.rates.all %}
                <tr>
                    <td>{{ rate.id }}</td>
                    <td>{{ rate.sale }}</td>
                    <td>{{ rate.buy }}</td>
                    <td>{{ rate.get_type_display }}</td>
                    <td>
                        <div class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton"
                                    data-toggle="dropdown"
                                    aria-haspopup="true" aria-expanded="false">
                                Actions
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <a class="dropdown-item" href="{% url 'currency:rate-details' rate.pk %}">Details</a>
                                <a class="dropdown-item" href="{% url 'currency:rate-update' rate.pk %}">Update</a>
                                <a class="dropdown-item" href="{% url 'currency:rate-delete' rate.pk %}">Delete</a>
                            </div>
                        </div>
                    </td>
                </tr>
            {% endfor %}
        </table>
    {% endfor %}
{% endblock %}